### ISSUE TITLE
Allow opacity on cover color for Featured Websites

### ISSUE THREAD

**Issue by benfairless** [Usernameeeeeeeee/startpage#1]
It's hard to necessarily know which box relates to which service. Would it be possible to have alpha values available where the underlying image is able to show through a semi-transparent cover?

**Comment by psaegert** [comment]
Yes, alpha values are available.
You can specify any valid CSS color (Settings > Content > [Page] > Color) like

rgb(255, 160, 160)
hsl(0, 100%, 50%)
#D06A78
#abc
red

and of course

#D06A7857
rgba(255, 160, 160, 0.5)

You can make each card transparent by setting its alpha value to 0, however its shadow will still be visible (might be a thing to fix in the future)

w3schools on colors: **https://www.w3schools.com/colors/default.asp**

**Comment by benfairless** [comment]
Thanks for the information!
